# -*- coding: utf-8 -*-
import json
import re

def add_vietnamese_accents(text):
    """Thay thế tiếng Việt không dấu bằng tiếng Việt có dấu"""
    replacements = {
        # Các từ phổ biến - cần đặt các cụm dài trước
        'Import thu vien': 'Import thư viện',
        'import thu vien': 'import thư viện',
        'thu vien': 'thư viện',
        'Thu vien': 'Thư viện',
        'da duoc': 'đã được',
        'thanh cong': 'thành công',
        'Tai du lieu': 'Tải dữ liệu',
        'tai du lieu': 'tải dữ liệu',
        'tien xu ly': 'tiền xử lý',
        'Tien xu ly': 'Tiền xử lý',
        'dinh nghia': 'định nghĩa',
        'Dinh nghia': 'Định nghĩa',
        'moi truong': 'môi trường',
        'Moi truong': 'Môi trường',
        'Thiet lap': 'Thiết lập',
        'thiet lap': 'thiết lập',
        'tach features': 'tách features',
        'Tach features': 'Tách features',
        'Cac ham': 'Các hàm',
        'cac ham': 'các hàm',
        'lay thong tin': 'lấy thông tin',
        'Lay thong tin': 'Lấy thông tin',
        'da bi loai': 'đã bị loại',
        'Da bi loai': 'Đã bị loại',
        'cho tung': 'cho từng',
        'Cho tung': 'Cho từng',
        'Dinh nghia': 'Định nghĩa',
        'ham ho tro': 'hàm hỗ trợ',
        'Danh gia': 'Đánh giá',
        'tra ve': 'trả về',
        'ket qua': 'kết quả',
        'Loai bo': 'Loại bỏ',
        'quan sat': 'quan sát',
        'doc lap': 'độc lập',
        'khong xet': 'không xét',
        'yeu to': 'yếu tố',
        'quoc gia': 'quốc gia',
        'thoi gian': 'thời gian',
        'Giu lai': 'Giữ lại',
        'xu huong': 'xu hướng',
        'lich su': 'lịch sử',
        'Xac dinh': 'Xác định',
        'cot can': 'cột cần',
        'So luong': 'Số lượng',
        'bao gom': 'bao gồm',
        'Chia du lieu': 'Chia dữ liệu',
        'theo thoi gian': 'theo thời gian',
        'Cau hinh': 'Cấu hình',
        'Them src': 'Thêm src',
        'vao path': 'vào path',
        
        # Notebook 01 specific
        'Libraries loaded successfully': 'Thư viện đã được tải thành công',
        'Load Raw Data': 'Tải dữ liệu gốc',
        
        # Notebook 03 specific
        'So sanh': 'So sánh',
        'Muc tieu': 'Mục tiêu',
        'Chung minh': 'Chứng minh',
        'Bay noi suy': 'Bẫy nội suy',
        'su khac biet': 'sự khác biệt',
        'giua': 'giữa',
        'Cau truc': 'Cấu trúc',
        'thi nghiem': 'thí nghiệm',
        'phuong phap': 'phương pháp',
        'chia du lieu': 'chia dữ liệu',
        'cach tiep can': 'cách tiếp cận',
        'thuat toan': 'thuật toán',
        'Tong cong': 'Tổng cộng',
        'su dung': 'sử dụng',
        'de hoc': 'để học',
        'Van de': 'Vấn đề',
        'nam truoc': 'năm trước',
        'co the': 'có thể',
        'gay': 'gây',
        'khi dung': 'khi dùng',
        'cua nam': 'của năm',
        'thuc cua': 'thực của',
        'dua': 'đưa',
        'se biet': 'sẽ biết',
        'thong qua': 'thông qua',
        'Giai phap': 'Giải pháp',
        'khong co': 'không có',
        'vi train': 'vì train',
        'Ket qua': 'Kết quả',
        'mong doi': 'mong đợi',
        'cao do': 'cao do',
        'noi suy': 'nội suy',
        'thap hon': 'thấp hơn',
        'ngoai suy': 'ngoại suy',
        'tot': 'tốt',
        'On dinh': 'Ổn định',
        'ca hai': 'cả hai',
        'Thiet lap': 'Thiết lập',
        'moi truong': 'môi trường',
        'tai du lieu': 'tải dữ liệu',
        'cho tung': 'cho từng',
        'Cac ham': 'Các hàm',
        'dinh nghia': 'định nghĩa',
        'Ham': 'Hàm',
        'nam': 'năm',
        'Canh bao': 'Cảnh báo',
        'tron lan': 'trộn lẫn',
        'cac nam': 'các năm',
        'nhin thay': 'nhìn thấy',
        'tuong lai': 'tương lai',
        'Phuong phap dung': 'Phương pháp đúng',
        'KHONG BAO GIO': 'KHÔNG BAO GIỜ',
        'du lieu': 'dữ liệu',
        'Tao bang': 'Tạo bảng',
        'tong hop': 'tổng hợp',
        'Phan tich': 'Phân tích',
        'sut giam': 'sụt giảm',
        'suy giam': 'suy giảm',
        'Bieu do': 'Biểu đồ',
        'luu tai': 'lưu tại',
        'Ket luan': 'Kết luận',
        'Xu ly': 'Xử lý',
        'nam trong': 'nằm trong',
        'Phat hien': 'Phát hiện',
        'quan trong': 'quan trọng',
        'TAI SAO': 'TẠI SAO',
        'MANH': 'MẠNH',
        'NGUYEN NHAN': 'NGUYÊN NHÂN',
        'GOC': 'GỐC',
        'hoc bang': 'học bằng',
        'tao cac': 'tạo các',
        'nguong': 'ngưỡng',
        'Vi du': 'Ví dụ',
        'Neu': 'Nếu',
        'chi hoat dong': 'chỉ hoạt động',
        'trong PHAM VI': 'trong PHẠM VI',
        'du doan': 'dự đoán',
        'chua thay': 'chưa thấy',
        'bao gio': 'bao giờ',
        'gia tri': 'giá trị',
        'cao nhat': 'cao nhất',
        'da thay': 'đã thấy',
        'SAI': 'SAI',
        'Hoc cong thuc': 'Học công thức',
        'tinh cho': 'tính cho',
        'BAT KY': 'BẤT KỲ',
        'nao': 'nào',
        'NGOAI SUY TOT': 'NGOẠI SUY TỐT',
        'vung anh huong': 'vùng ảnh hưởng',
        'xung quanh': 'xung quanh',
        'diem training': 'điểm training',
        'gan pham vi': 'gần phạm vi',
        'van co the': 'vẫn có thể',
        'nhe vi': 'nhẹ vì',
        'qua xa': 'quá xa',
        'Tuong duong': 'Tương đương',
        'giup': 'giúp',
        'dang ke': 'đáng kể',
        'nhung': 'nhưng',
        'KHONG cuu duoc': 'KHÔNG cứu được',
        'chi can': 'chỉ cần',
        'dien vao': 'điền vào',
        'cho trong': 'chỗ trống',
        'qua khu': 'quá khứ',
        'phai': 'phải',
        'that bai': 'thất bại',
        'giam': 'giảm',
        'Khuyen nghi': 'Khuyến nghị',
        'PHAI dung': 'PHẢI dùng',
        'cho bai toan': 'cho bài toán',
        'du bao': 'dự báo',
        'chuoi thoi gian': 'chuỗi thời gian',
        'de tranh': 'để tránh',
        'lua chon': 'lựa chọn',
        'tot nhat': 'tốt nhất',
        'KHONG phu hop': 'KHÔNG phù hợp',
        'doc lap': 'độc lập',
        'co the dung': 'có thể dùng',
        'trong': 'trong',
        'trung gian': 'trung gian',
        'neu can': 'nếu cần',
        'phi tuyen': 'phi tuyến',
        
        # Thêm các từ khác
        'tranh data leakage': 'tránh data leakage',
        'LUU Y': 'LƯU Ý',
        'VE': 'VỀ',
        'loai bo': 'loại bỏ',
        'GIU': 'GIỮ',
        'Ly do': 'Lý do',
        'Voi': 'Với',
        'biet': 'biết',
        'Nhan xet': 'Nhận xét',
        'chuyen tu': 'chuyển từ',
        'sang': 'sang',
        'phu thuoc': 'phụ thuộc',
        'hoan toan': 'hoàn toàn',
        'hien tai': 'hiện tại',
        'Rat on dinh': 'Rất ổn định',
        'rat nhe': 'rất nhẹ',
        'dac diem': 'đặc điểm',
        'rieng cua': 'riêng của',
        'tung': 'từng',
        'Van': 'Vẫn',
        'co ban': 'cơ bản',
        'Rat cao': 'Rất cao',
        'Giam manh': 'Giảm mạnh',
        'Van cao': 'Vẫn cao',
        'It': 'Ít',
        'Cao': 'Cao',
        
        # Notebook 02 specific
        'du lieu chung': 'dữ liệu chung',
        'Xu ly missing values': 'Xử lý missing values',
        'Tao lag features': 'Tạo lag features',
        'Loc quoc gia': 'Lọc quốc gia',
        'du nam': 'đủ năm',
        'Log transform': 'Log transform',
        'cot lech': 'cột lệch',
        'Luu file': 'Lưu file',
        'da xu ly': 'đã xử lý',
        'Kiem tra': 'Kiểm tra',
        'ket qua': 'kết quả',
        'cuoi cung': 'cuối cùng',
        
        # Thêm các từ còn thiếu
        'de lay': 'để lấy',
        'De lay': 'Để lấy',
        'thong tin': 'thông tin',
        'Thong tin': 'Thông tin',
        'bi loai': 'bị loại',
        'Bi loai': 'Bị loại',
        'tung model': 'từng model',
        'Tung model': 'Từng model',
    }
    
    result = text
    for old, new in replacements.items():
        result = result.replace(old, new)
    return result

def process_notebook(filepath):
    """Xử lý một notebook"""
    with open(filepath, 'r', encoding='utf-8') as f:
        notebook = json.load(f)
    
    for cell in notebook['cells']:
        if 'source' in cell:
            new_source = []
            for line in cell['source']:
                new_source.append(add_vietnamese_accents(line))
            cell['source'] = new_source
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, ensure_ascii=False, indent=1)
    
    print(f"Đã cập nhật: {filepath}")

# Xử lý tất cả notebooks
process_notebook('notebooks_new/01_Data_Exploration.ipynb')
process_notebook('notebooks_new/02_Data_Preprocessing.ipynb')
process_notebook('notebooks_new/03_Phase0_Random_vs_TimeSeries.ipynb')

print("\nHoàn thành!")
